name: Deploy Frontend to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/app/**' 
  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      - name: Generate backend-config.hcl (Frontend)
        working-directory: frontend/terraform
        run: |
          cat <<EOF > backend-config.hcl
          bucket         = "${{ secrets.S3_REMOTE_FRONT }}"
          key            = "terraform.tfstate"
          region         = "${{ secrets.AWS_REGION }}"
          dynamodb_table = "${{ secrets.STATE_LOCK_FRONT }}"
          encrypt        = true
          EOF

      - name: Generate terraform.tfvars
        working-directory: frontend/terraform
        run: |
          cat <<EOF > terraform.tfvars
          aws_region = "${{ secrets.AWS_REGION }}"
          domain_name = "${{ secrets.DOMAIN_NAME }}"
          acm_certificate_arn = "${{ secrets.ACM_CERTIFICATE_ARN }}"
          s3_bucket_name = "${{ secrets.S3_BUCKET_NAME }}"
          hosted_zone_id = "${{ secrets.HOSTED_ZONE_ID }}"
          s3_remote_front = "${{ secrets.S3_REMOTE_FRONT }}"
          state_lock_front = "${{ secrets.STATE_LOCK_FRONT }}"
          EOF

      - name: Initialize Terraform
        working-directory: frontend/terraform
        run: terraform init -backend-config="backend-config.hcl"

      - name: Plan Terraform Changes
        working-directory: frontend/terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: frontend/terraform
        run: terraform apply -auto-approve